/**
 * The full exercise library, as [name, equipment] per muscle group.
 *
 * Transcribed verbatim from the source list — names are kept exactly as given
 * so they match elsewhere. A few exercises deliberately appear under two muscle
 * groups (shrugs under Shoulders and Traps, deadlifts under Back and Glutes);
 * those are separate library entries, which is intended.
 */
const BY_MUSCLE = {
  chest: [
    ['Bench Press (Cambered Bar)', 'Barbell'],
    ['Bench Press (Decline)', 'Barbell'],
    ['Bench Press (Incline, Medium Grip)', 'Barbell'],
    ['Bench Press (Incline, Narrow Grip)', 'Barbell'],
    ['Bench Press (Incline, Wide Grip)', 'Barbell'],
    ['Bench Press (Medium Grip)', 'Barbell'],
    ['Bench Press (Narrow Grip)', 'Barbell'],
    ['Bench Press (Wide Grip)', 'Barbell'],
    ['Cable Chest Press', 'Cable'],
    ['Cable Flye', 'Cable'],
    ['Cable Flye (Bent Over)', 'Cable'],
    ['Cable Flye (High)', 'Cable'],
    ['Cable Flye (Seated)', 'Cable'],
    ['Cable Flye (Underhand)', 'Cable'],
    ['Dip (Chest-Focused)', 'Bodyweight Only'],
    ['Dip (Weighted, Chest-Focused)', 'Bodyweight Loadable'],
    ['Dumbbell Flye (Flat)', 'Dumbbell'],
    ['Dumbbell Flye (Incline)', 'Dumbbell'],
    ['Dumbbell Press (Flat)', 'Dumbbell'],
    ['Dumbbell Press (High Incline)', 'Dumbbell'],
    ['Dumbbell Press (Low Incline)', 'Dumbbell'],
    ['Dumbbell Press (Medium Incline)', 'Dumbbell'],
    ['Dumbbell Press Flye (Flat)', 'Dumbbell'],
    ['Dumbbell Press Flye (Incline)', 'Dumbbell'],
    ['Hammer Machine Chest Press (Flat)', 'Machine'],
    ['Hammer Machine Chest Press (Incline)', 'Machine'],
    ['Machine Chest Press', 'Machine'],
    ['Machine Chest Press (Incline)', 'Machine'],
    ['Machine Flye', 'Machine'],
    ['Pec Dec Flye', 'Machine'],
    ['Pushup', 'Bodyweight Only'],
    ['Pushup (Deficit)', 'Bodyweight Only'],
    ['Pushup (Narrow Grip)', 'Bodyweight Only'],
    ['Pushup (Weighted, Narrow Grip)', 'Bodyweight Loadable'],
    ['Pushup (Weighted, Normal Grip)', 'Bodyweight Loadable'],
    ['Smith Machine Bench Press (Medium Grip)', 'Smith Machine'],
    ['Smith Machine Bench Press (Narrow Grip)', 'Smith Machine'],
    ['Smith Machine Bench Press (Wide Grip)', 'Smith Machine'],
    ['Smith Machine Press (High Incline, Medium Grip)', 'Smith Machine'],
    ['Smith Machine Press (High Incline, Narrow Grip)', 'Smith Machine'],
    ['Smith Machine Press (High Incline, Wide Grip)', 'Smith Machine'],
    ['Smith Machine Press (Incline, Medium Grip)', 'Smith Machine'],
    ['Smith Machine Press (Incline, Wide Grip)', 'Smith Machine'],
    ['Smith Machine Press (Low Incline, Medium Grip)', 'Smith Machine'],
    ['Smith Machine Press (Low Incline, Narrow Grip)', 'Smith Machine'],
    ['Smith Machine Press (Low Incline, Wide Grip)', 'Smith Machine'],
    ['Smith Machine Press (Medium Incline, Narrow Grip)', 'Smith Machine'],
  ],

  back: [
    ['Assisted Pullup (Normal Grip)', 'Machine Assistance'],
    ['Assisted Pullup (Parallel Grip)', 'Machine Assistance'],
    ['Assisted Pullup (Underhand Grip)', 'Machine Assistance'],
    ['Assisted Pullup (Wide Grip)', 'Machine Assistance'],
    ['Back Extension', 'Bodyweight Loadable'],
    ['Back Extension (Flexion)', 'Bodyweight Loadable'],
    ['Barbell Bent Over Row', 'Barbell'],
    ['Barbell Flexion Row', 'Barbell'],
    ['Barbell Pullover', 'Barbell'],
    ['Barbell Row to Chest', 'Barbell'],
    ['Cable Flexion Row', 'Cable'],
    ['Cable Pullover', 'Cable'],
    ['Cambered Bar Row', 'Barbell'],
    ['Chest Supported Row', 'Machine'],
    ['Deadlift', 'Barbell'],
    ['Deadlift (Flexion)', 'Barbell'],
    ['Dual Cable Pullover', 'Cable'],
    ['Dumbbbell Flexion Row', 'Dumbbell'],
    ['Dumbbell Pullover', 'Dumbbell'],
    ['Dumbbell Row (2-Arm)', 'Dumbbell'],
    ['Dumbbell Row (2-Arm, Incline)', 'Dumbbell'],
    ['Dumbbell Row (Single-Arm, Supported)', 'Dumbbell'],
    ['Dumbbell Row to Hips', 'Dumbbell'],
    ['EZ Bar Row (Underhand)', 'Barbell'],
    ['Hammer Machine Row (High)', 'Machine'],
    ['Hammer Machine Row (Low)', 'Machine'],
    ['Inverted Row', 'Bodyweight Only'],
    ['Landmine Row', 'Barbell'],
    ['Machine Chest Supported Row', 'Machine'],
    ['Machine Pulldown', 'Machine'],
    ['Machine Pullover', 'Machine'],
    ['Meadows Row', 'Barbell'],
    ['Pulldown (Narrow Grip)', 'Cable'],
    ['Pulldown (Normal Grip)', 'Cable'],
    ['Pulldown (Parallel Grip)', 'Cable'],
    ['Pulldown (Single-Arm)', 'Cable'],
    ['Pulldown (Straight Arm)', 'Cable'],
    ['Pulldown (Underhand Grip)', 'Cable'],
    ['Pulldown (Upright Torso to Abs)', 'Cable'],
    ['Pulldown (Wide Grip)', 'Cable'],
    ['Pullup (Normal Grip)', 'Bodyweight Only'],
    ['Pullup (Parallel Grip)', 'Bodyweight Only'],
    ['Pullup (Underhand Grip)', 'Bodyweight Only'],
    ['Pullup (Weighted, Normal Grip)', 'Bodyweight Loadable'],
    ['Pullup (Weighted, Parallel Grip)', 'Bodyweight Loadable'],
    ['Pullup (Weighted, Underhand Grip)', 'Bodyweight Loadable'],
    ['Pullup (Weighted, Wide Grip)', 'Bodyweight Loadable'],
    ['Pullup (Wide Grip)', 'Bodyweight Only'],
    ['Seal Row', 'Barbell'],
    ['Seated Cable Row', 'Cable'],
    ['Seated Cable Row (Single-Arm)', 'Cable'],
    ['Smith Machine Row', 'Smith Machine'],
    ['T-Bar Row', 'Machine'],
  ],

  shoulders: [
    ['Arnold Press', 'Dumbbell'],
    ['Barbell Bent Over Shrug', 'Barbell'],
    ['Barbell Facepull', 'Barbell'],
    ['Barbell Front Raise', 'Barbell'],
    ['Barbell Front Raise (EZ Bar, Underhand)', 'Barbell'],
    ['Barbell Front Raise (Overhand)', 'Barbell'],
    ['Barbell Shoulder Press (Seated)', 'Barbell'],
    ['Barbell Shoulder Press (Standing)', 'Barbell'],
    ['Barbell Shrug', 'Barbell'],
    ['Barbell Upright Row', 'Barbell'],
    ['Cable Bent Over Shrug', 'Cable'],
    ['Cable Cross Body Bent Lateral Raise', 'Cable'],
    ['Cable Cross Body Lateral Raise', 'Cable'],
    ['Cable Front Raise (Overhand)', 'Cable'],
    ['Cable Front Raise (Underhand)', 'Cable'],
    ['Cable Lateral Raise (Single-Arm)', 'Cable'],
    ['Cable Leaning Lateral Raise', 'Cable'],
    ['Cable Rope Facepull', 'Cable'],
    ['Cable Rope Facepull (Kneeling)', 'Cable'],
    ['Cable Shrug', 'Cable'],
    ['Cable Side Shrug', 'Cable'],
    ['Cable Single Arm Rear Delt Raise', 'Cable'],
    ['Cable Single Arm Side Shrug', 'Cable'],
    ['Cable Upright Row', 'Cable'],
    ['Dumbbell Bent Lateral Raise', 'Dumbbell'],
    ['Dumbbell Bent Over Shrug', 'Dumbbell'],
    ['Dumbbell Facepull', 'Dumbbell'],
    ['Dumbbell Facepull (Incline)', 'Dumbbell'],
    ['Dumbbell Front Raise', 'Dumbbell'],
    ['Dumbbell Lateral Raise', 'Dumbbell'],
    ['Dumbbell Lateral Raise (Incline)', 'Dumbbell'],
    ['Dumbbell Lateral Raise (Seated)', 'Dumbbell'],
    ['Dumbbell Lateral Raise (Super ROM)', 'Dumbbell'],
    ['Dumbbell Lateral Raise (Thumbs Down)', 'Dumbbell'],
    ['Dumbbell Lateral Raise (Top Hold)', 'Dumbbell'],
    ['Dumbbell Leaning Shrug', 'Dumbbell'],
    ['Dumbbell Press (High Incline)', 'Dumbbell'],
    ['Dumbbell Shoulder Press (Seated)', 'Dumbbell'],
    ['Dumbbell Shoulder Press (Standing)', 'Dumbbell'],
    ['Dumbbell Shrug', 'Dumbbell'],
    ['Dumbbell Shrug (Seated)', 'Dumbbell'],
    ['Dumbbell Upright Row', 'Dumbbell'],
    ['Freemotion Rear Delt Flyes', 'Freemotion'],
    ['Freemotion Rear Delt Flyes (Paused)', 'Freemotion'],
    ['Freemotion Y-Raises', 'Freemotion'],
    ['Freemotion Y-Raises (Paused)', 'Freemotion'],
    ['Machine Lateral Raise', 'Machine'],
    ['Machine Reverse Flye', 'Machine'],
    ['Machine Shoulder Press', 'Machine'],
    ['Smith Machine Shoulder Press (Seated)', 'Smith Machine'],
    ['Smith Machine Upright Row', 'Smith Machine'],
  ],

  biceps: [
    ['Barbell Curl (Narrow Grip)', 'Barbell'],
    ['Barbell Curl (Normal Grip)', 'Barbell'],
    ['Bayesian Curl', 'Cable'],
    ['Cable Curl', 'Cable'],
    ['Cable Curl (EZ Bar)', 'Cable'],
    ['Cable Curl (EZ Bar, Wide Grip)', 'Cable'],
    ['Cable Curl (Single-Arm)', 'Cable'],
    ['Cable Hammer Curl (Rope)', 'Cable'],
    ['Cable Rope Twist Curl', 'Cable'],
    ['Concentration Curl', 'Dumbbell'],
    ['Decline Dumbbell Curl', 'Dumbbell'],
    ['Dumbbell Curl (2-Arm)', 'Dumbbell'],
    ['Dumbbell Curl (Alternating)', 'Dumbbell'],
    ['Dumbbell Curl (Incline)', 'Dumbbell'],
    ['Dumbbell Preacher Curl (Single-Arm)', 'Dumbbell'],
    ['Dumbbell Spider Curl', 'Dumbbell'],
    ['Dumbbell Twist Curl', 'Dumbbell'],
    ['EZ Bar Curl (Narrow Grip)', 'Barbell'],
    ['EZ Bar Curl (Normal Grip)', 'Barbell'],
    ['EZ Bar Curl (Wide Grip)', 'Barbell'],
    ['EZ Bar Preacher Curl', 'Barbell'],
    ['EZ Bar Spider Curl', 'Barbell'],
    ['Freemotion Curl (Facing Away)', 'Freemotion'],
    ['Freemotion Curl (Facing Machine)', 'Freemotion'],
    ['Freemotion Curl (Single-Arm)', 'Freemotion'],
    ['Hammer Curl', 'Dumbbell'],
    ['Hammer Preacher Curl', 'Dumbbell'],
    ['Lying Biceps Dumbbell Curl', 'Dumbbell'],
    ['Lying Cable Curl', 'Cable'],
    ['Lying Dumbbell Curl', 'Dumbbell'],
    ['Machine Preacher Curl', 'Machine'],
  ],

  triceps: [
    ['Assisted Dip', 'Machine Assistance'],
    ['Barbell Overhead Triceps Extension', 'Barbell'],
    ['Barbell Overhead Triceps Extension (Seated)', 'Barbell'],
    ['Barbell Skullcrusher', 'Barbell'],
    ['Bench Press (Close Grip)', 'Barbell'],
    ['Cable Overhead Triceps Extension', 'Cable'],
    ['Cable Overhead Triceps Extension (Rope)', 'Cable'],
    ['Cable Tricep Kickback', 'Cable'],
    ['Cable Triceps Pushdown (Bar)', 'Cable'],
    ['Cable Triceps Pushdown (Rope)', 'Cable'],
    ['Cable Triceps Pushdown (Single-Arm)', 'Cable'],
    ['Dip (Triceps-Focused)', 'Bodyweight Only'],
    ['Dip (Weighted, Triceps-Focused)', 'Bodyweight Loadable'],
    ['Dip Machine', 'Machine'],
    ['Dumbbell Overhead Extension', 'Dumbbell'],
    ['Dumbbell Overhead Extension (Single-Arm)', 'Dumbbell'],
    ['Dumbbell Skullcrusher', 'Dumbbell'],
    ['EZ Bar Overhead Triceps Extension', 'Barbell'],
    ['EZ Bar Overhead Triceps Extension (Seated)', 'Barbell'],
    ['EZ Bar Skullcrusher', 'Barbell'],
    ['Inverted Skullcrusher', 'Bodyweight Only'],
    ['JM Press', 'Barbell'],
    ['Machine Triceps Extension', 'Machine'],
    ['Machine Triceps Pushdown', 'Machine'],
    ['Smith Machine JM Press', 'Smith Machine'],
    ['Smith Machine Skullcrusher', 'Smith Machine'],
  ],

  quads: [
    ['Barbell Split Squat', 'Barbell'],
    ['Barbell Squat (Cambered Bar)', 'Barbell'],
    ['Barbell Squat (Close Stance, Feet Forward)', 'Barbell'],
    ['Barbell Squat (High Bar)', 'Barbell'],
    ['Barbell Squat (Narrow Stance)', 'Barbell'],
    ['Barbell Squat (Safety Bar)', 'Barbell'],
    ['Belt Squat', 'Machine'],
    ['Bodyweight Squat (2/3)', 'Bodyweight Only'],
    ['Bulgarian Split Squat (Quad-Focused)', 'Dumbbell'],
    ['Dumbbell Front Squat', 'Dumbbell'],
    ['Front Squat', 'Barbell'],
    ['Front Squat (Cross Grip)', 'Barbell'],
    ['Goblet Squat', 'Dumbbell'],
    ['Hack Squat', 'Machine'],
    ['Hip Adduction', 'Machine'],
    ['Leg Extension', 'Machine'],
    ['Leg Press', 'Machine'],
    ['Pendulum Squat', 'Machine'],
    ['Rogers Squat', 'Machine'],
    ['Single Leg Extension', 'Machine'],
    ['Single Leg Press', 'Machine'],
    ['Sissy Squat (Machine)', 'Bodyweight Only'],
    ['Sissy Squat (No Machine)', 'Bodyweight Only'],
    ['Smith Machine Squat (Feet Forward)', 'Smith Machine'],
    ['Walking Lunges (Quad-Focused, Barbell)', 'Barbell'],
    ['Walking Lunges (Quad-Focused, Bodyweight)', 'Bodyweight Only'],
    ['Walking Lunges (Quad-Focused, Dumbbell)', 'Dumbbell'],
  ],

  hamstrings: [
    ['Back Raise (45 degree)', 'Bodyweight Only'],
    ['Back Raise (Glute Ham Deck)', 'Bodyweight Only'],
    ['Back Raise (weighted)', 'Freemotion'],
    ['Barbell Good Morning (Cambered Bar)', 'Barbell'],
    ['Barbell Good Morning (High Bar)', 'Barbell'],
    ['Barbell Good Morning (Low Bar)', 'Barbell'],
    ['Barbell Good Morning (Safety Bar)', 'Barbell'],
    ['Dumbbell Stiff Legged Deadlift', 'Dumbbell'],
    ['Lying Leg Curl', 'Machine'],
    ['Nordic Curl', 'Bodyweight Only'],
    ['Rogers Good Morning', 'Machine'],
    ['Seated Leg Curl', 'Machine'],
    ['Single Leg Romanian Deadlift', 'Dumbbell'],
    ['Single-Leg Leg Curl', 'Machine'],
    ['Smith Machine Good Morning', 'Smith Machine'],
    ['Stiff-Legged Deadlift', 'Barbell'],
  ],

  glutes: [
    ['Barbell Hip Thrust', 'Barbell'],
    ['Barbell Squat (Sumo Stance)', 'Barbell'],
    ['Belt Squat (Wide Stance)', 'Machine'],
    ['Bulgarian Split Squat (Glute-Focused)', 'Dumbbell'],
    ['Cable Kickback', 'Cable'],
    ['Cable Pull Through', 'Cable'],
    ['Deadlift', 'Barbell'],
    ['Deadlift (Deficit)', 'Barbell'],
    ["Deadlift (Deficit 25's)", 'Barbell'],
    ['Deadlift (Sumo Stance)', 'Barbell'],
    ['Deadlift (Sumo Stance, Deficit)', 'Barbell'],
    ['Dumbbell Hip Thrust (Single Leg)', 'Dumbbell'],
    ['Dumbbell Split Squat', 'Dumbbell'],
    ['Front Foot Elevated Smith Lunge', 'Smith Machine'],
    ['Hip Abduction Machine', 'Machine'],
    ['Machine Glute Kickback', 'Machine'],
    ['Machine Hip Thrust', 'Machine'],
    ['Reverse Hyper', 'Machine'],
    ['Reverse Lunge (Barbell)', 'Barbell'],
    ['Reverse Lunge (Dumbbell)', 'Dumbbell'],
    ['Rogers Reverse Lunge', 'Machine'],
    ['Smith Machine Split Squat', 'Smith Machine'],
    ['Trap Bar Deadlift', 'Barbell'],
    ['Walking Lunges (Glute-Focused, Barbell)', 'Barbell'],
    ['Walking Lunges (Glute-Focused, Bodyweight)', 'Bodyweight Only'],
    ['Walking Lunges (Glute-Focused, Dumbbell)', 'Dumbbell'],
  ],

  calves: [
    ['Belt Squat Calves', 'Machine'],
    ['Calf Machine', 'Machine'],
    ['Donkey Calf Raise', 'Machine'],
    ['Leg Press Calves', 'Machine'],
    ['Smith Machine Calves', 'Smith Machine'],
    ['Stair Calves', 'Bodyweight Only'],
    ['Stair Calves (Single Leg)', 'Bodyweight Only'],
    ['Standing Calf Raise', 'Machine'],
  ],

  abs: [
    ['Ab Wheel', 'Bodyweight Only'],
    ['Cable Rope Crunch', 'Cable'],
    ['Elbow Knee Raise', 'Machine Assistance'],
    ['Hanging Knee Raise', 'Bodyweight Only'],
    ['Hanging Straight Leg Raise', 'Bodyweight Only'],
    ['Knee to abs', 'Bodyweight Only'],
    ['Leg lift (bench)', 'Bodyweight Only'],
    ['Machine Crunch', 'Machine'],
    ['Modified Candlestick', 'Bodyweight Only'],
    ['Reaching Sit-Up', 'Bodyweight Only'],
    ['Slant Board Sit-Up (Weighted)', 'Bodyweight Loadable'],
    ['V-Up (Weighted)', 'Bodyweight Loadable'],
  ],

  forearms: [
    ['Barbell Standing Wrist Curl', 'Barbell'],
    ['Cable Wrist Curl', 'Cable'],
    ['Dumbbell Bench Wrist Curl', 'Dumbbell'],
    ['Dumbbell Standing Wrist Curl', 'Dumbbell'],
    ['Grip Roller', 'Machine'],
    ['Reverse Curl', 'Barbell'],
  ],

  traps: [
    ['Barbell Bent Over Shrug', 'Barbell'],
    ['Barbell Shrug', 'Barbell'],
    ['Cable Bent Over Shrug', 'Cable'],
    ['Cable Shrug', 'Cable'],
    ['Cable Side Shrug', 'Cable'],
    ['Cable Single Arm Side Shrug', 'Cable'],
    ['Dumbbell Bent Over Shrug', 'Dumbbell'],
    ['Dumbbell Leaning Shrug', 'Dumbbell'],
    ['Dumbbell Shrug', 'Dumbbell'],
    ['Dumbbell Shrug (Seated)', 'Dumbbell'],
    ['Machine Shrug', 'Machine'],
    ['Smith Machine Shrug', 'Smith Machine'],
  ],
};

export const CATALOG = Object.entries(BY_MUSCLE).flatMap(([muscle, rows]) =>
  rows.map(([name, equipment]) => ({ name, muscle, equipment })));
